# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About Me"
  pageref = "about-me"
  weight = 1

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Resources"
  pageRef = "resources"
  weight = 20

#Below is the submenu for Resources

[[main]]
  name = "Main Platforms"
  parent = "Resources"
  pageRef = "resources/main-platforms"
  weight = 10

[[main]]
  name = "Offensive Resources"
  parent = "Resources"
  pageRef = "resources/offensive-resources"
  weight = 20

[[main]]
  name = "Defensive Resources"
  parent = "Resources"
  pageRef = "resources/defensive-resources"
  weight = 30

[[main]]
  name = "CTF Resources"
  parent = "Resources"
  pageRef = "resources/ctf-resources"
  weight = 40

[[main]]
  name = "Blogs"
  parent = "Resources"
  pageRef = "resources/blogs"
  weight = 50

[[main]]
  name = "Programming Resources"
  parent = "Resources"
  pageRef = "resources/programming"
  weight = 60

[[main]]
  name = "Training Resources"
  parent = "Resources"
  pageRef = "resources/training"
  weight = 70

[[main]]
  name = "Home Lab Resources"
  parent = "Resources"
  pageRef = "resources/home-lab"
  weight = 80

[[main]]
  name = "Physical Tools"
  parent = "Resources"
  pageRef = "resources/physical"
  weight = 90

[[main]]
  name = "Blockchain"
  parent = "Resources"
  pageRef = "resources/blockchain"
  weight = 100



#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


#[[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

#[[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

#[[footer]]
  #name = "Authors"
  #pageref = "authors"
  #weight = 3
